### ISSUE TITLE
Can't encode PublicKeyCredential

### ISSUE THREAD

**Issue by sachaw** [lifaon74/jbson#1]
I am implementing WebAuthn into one of my projects, i'm using JBSON to encode the client and server responses as they contain arraybuffers, however, when I attempt to encode a credential, JBSON throws an error ```TypeError: Unsupported type : [object PublicKeyCredential]```

from the following code:
```
const credential= await navigator.credentials.create({
    ...
  })
const bsonCredential = EncodeToJBSON(credential)
```

Thanks in advance.

**Comment by lifaon74** [comment]
Yes, this is normal. Native types have private attributes that can't be access because they only exist on the js engine (so in c++). Thereby native classes can't be cloned if we can't clone them with plain JS.

Moreover, same applies for getters and setters, non enumerable properties, or inherited properties (prototype). 

This algorithm follows the structured clone algorithm (found here: https://html.spec.whatwg.org/multipage/structured-data.html#safe-passing-of-structured-data)

You may see it with: 

```js
const cloned = {
  ...await navigator.credentials
    .get({ 'password': true })
}; // oops 'cloned' is an empty object, because properties are inherited for a prototype (Object.keys return empty array)
````

Instead do:
```js
const credentials = await navigator.credentials.get({ password: true });
const _credentials = ['iconURL', 'id', 'name', 'password', 'type'].reduce((obj, property) => {
  obj[property] = credentials[property];
}, {});
```
